# Generated by Django 4.2.5 on 2023-09-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_car_delete_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Item',
        ),
    ]
